sudo: false
cache:
  directories:
    - "$HOME/.m2"
language: java
before_script:
  - cd src
script:
  - rm -rf /home/travis/.m2/repository/org/apache/xmlgraphics/fop
  - mvn -B -U -T2 -fae -Prelease clean install
notifications:
  email:
    on_success: never
    on_failure: never
os:
  - linux
  - osx
matrix:
  allow_failures:
    - os: osx
  include:
  # additional builds on linux w/ openjdk7 and oraclejdk8
    - os: linux
      jdk: openjdk7
    - os: linux
      jdk: oraclejdk8
before_install:
   # JAVA_HOME is not available on OSX, set it to allow Maven run
   - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export JAVA_HOME=$(/usr/libexec/java_home); fi
